name: Test with existing Pyre config

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # For delibrate_vulnerable_flask_app
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.6'

      - name: Setup deliberately_vulnerable_flask_app
        run: |
          git clone https://github.com/facebook/pyre-check test/pyre-check
          (cd test/pyre-check/documentation/deliberately_vulnerable_flask_app/ && . ./setup.sh)
          cat test/pyre-check/documentation/deliberately_vulnerable_flask_app/.pyre_configuration

      # For testing infer-types option
      - name: Delete existing type annotations in app.py
        run: |
          sed -i 's/ -> None:/:/g' test/pyre-check/documentation/deliberately_vulnerable_flask_app/app.py
          cat test/pyre-check/documentation/deliberately_vulnerable_flask_app/app.py

      - name: Run Pysa Action
        uses: ./
        with:
          repo-directory: 'test/pyre-check/documentation/deliberately_vulnerable_flask_app'
          use-nightly: false
          requirements-path: 'requirements.txt'
          include-default-sapp-filters: true
          sapp-filters-directory: test/custom-filters
          infer-types: true
